import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Urdu translations from the current translations.ts
const urduTranslations = {
  "appTitle": "نور کنیکٹ",
  "home": "ہوم",
  "quran": "قرآن",
  "qibla": "قبلہ",
  "settings": "ترتیبات",
  "profile": "پروفائل",
  "loading": "لوڈ ہو رہا ہے",
  "services": "خدمات",
  "nextPrayer": "اگلی نماز",
  "todaysPrayers": "آج کی نمازیں",
  "viewAll": "سبھی دیکھیں",
  "dailyAyah": "روزانہ آیت",
  "dailyHadith": "روزانہ حدیث",
  "readMore": "مزید پڑھیں",
  "share": "بانٹیں",
  "qazaTracker": "قازا ٹریکر",
  "ramadanMode": "رمضان موڈ",
  "menstrualMode": "ماہواری موڈ",
  "zakatCalculator": "زکوٰہ کیلکولیٹر",
  "islamicQuiz": "اسلامی کوئز",
  "namesOfAllah": "اللہ کے ۹۹ نام",
  "tasbih": "تسبیح",
  "tracker": "ٹریکر",
  "calc": "کیلکولیٹر",
  "mode": "موڈ",
  "islamic": "اسلامی",
  "ofAllah": "اللہ کے",
  "direction": "سمت",
  "fajr": "فجر",
  "sunrise": "طلوع آفتاب",
  "dhuhr": "ظہر",
  "asr": "عصر",
  "maghrib": "مغرب",
  "isha": "عشاء",
  "imsak": "امساک",
  "ishraq": "اشراق",
  "duha": "ضحی",
  "tahajjud": "تہجد",
  "midnight": "نصف رات",
  "manual": "دستی",
  "joinDiscord": "ہمارے ڈسکورڈ میں شامل ہوں",
  "contactDeveloper": "ڈویلپر سے رابطہ کریں",
  "makeDua": "میرے لیے دعا کریں",
  "upcoming": "آنے والا",
  "end": "اختتام",
  "searchSurah": "سورہ تلاش کریں...",
  "ayahs": "آیات",
  "juz": "جز",
  "surahs": "سورتیں",
  "locationDetected": "مقام کا پتہ لگ گیا",
  "locationDetectionFailed": "مقام کا پتہ لگانے میں ناکام",
  "pleaseEnableLocationPermissions": "براہ کرم مقام کی اجازتاں فعال کریں",
  "menstrualModeEnded": "ماہواری موڈ ختم ہو گیا",
  "menstrualModeEnabled": "ماہواری موڈ فعال ہو گیا",
  "prayerReminderSchedulingResumed": "نماز کی یاد دہانی کا شیڈول دوبارہ شروع ہو گیا.",
  "prayerRemindersPaused": "جب یہ موڈ فعال ہے تو نماز کی یاد دہانیاں اور خودکار قازا مطابقت روک دی جاتی ہیں۔",
  "failedToClearPrayerNotifications": "نماز کی نوٹیفیکیشنز صاحب کرنے میں ناکام:",
  "salamGreetingEnabled": "سلام سلامتی فعال",
  "salamGreetingDisabled": "سلام سلامتی غیر فعال",
  "notificationPermissionDenied": "نوٹیفیکیشن اجازت مسترد کردی گئی",
  "pleaseEnableNotificationsInBrowser": "براہ کرم اپنے براؤزر کی ترتیبات میں نوٹیفیکیشنز فعال کریں",
  "notificationsEnabled": "✅ نوٹیفیکیشنز فعال ہو گئیں!",
  "youllReceivePrayerReminders": "آب اب نماز کے اوقات اور اسلامی واقعات کی یاد دہانیاں حاصل کریں گے۔",
  "permissionDenied": "اجازت مسترد",
  "goToAndroidSettings": "اینڈرائیڈ ترتیبات پر جائیں → ایپس → نور کنیکٹ → نوٹیفیکیشنز اور انہیں آن کریں۔",
  "clickLockIconAllowNotifications": "براؤزر ایڈریس بار میں لاک آئکن پر کلک کریں اور نوٹیفیکیشنز کی اجازت دیں۔",
  "testNotificationSent": "ٹیسٹ نوٹیفیکیشن بھیجی گئی",
  "failedToSendNotification": "نوٹیفیکیشن بھیجنے میں ناکام",
  "pleaseCheckDeviceNotificationSettings": "براہ کرم اپنے ڈیوائس کی نوٹیفیکیشن ترتیبات چیک کریں۔",
  "prayerNotificationsEnabled": "نماز کی نوٹیفیکیشنز فعال",
  "prayerNotificationsDisabled": "نماز کی نوٹیفیکیشنز غیر فعال",
  "prayerRemindersScheduled": "نماز کی یاد دہانیاں خودکار شیڈول ہوں گی",
  "prayerRemindersCancelled": "نماز کی یاد دہانیاں منسوخ کر دی گئیں",
  "failedToUpdatePrayerNotificationSettings": "نماز کی نوٹیفیکیشن ترتیبات اپ ڈیٹ کرنے میں ناکام:",
  "couldNotUpdatePrayerNotificationSettings": "نماز کی نوٹیفیکیشن ترتیبات اپ ڈیٹ نہیں ہو سکیں۔",
  "prayerNotificationsCleared": "نماز کی نوٹیفیکیشنز صاف ہو گئیں",
  "allScheduledPrayerRemindersCancelled": "تمام شیڈول شدہ نماز کی یاد دہانیاں منسوخ کر دی گئیں",
  "madhabShafi": "مذہب: شافعی",
  "madhabHanafi": "مذہب: حنفی",
  "calculationMethodUpdated": "حساب طریقہ اپ ڈیٹ ہو گیا",
  "quranFontChanged": "قرآن فونٹ تبدیل ہو گیا",
  "nowUsingFont": "اب استعمال ہو رہا ہے",
  "creatingBackup": "بیک اپ بن رہا ہے...",
  "pleaseWaitBackup": "براہ کرم انتظار کریں جب ہم آپ کی بیک اپ فائل تیار کرتے ہیں۔",
  "backupComplete": "✅ بیک اپ مکمل",
  "backupDownloadedSuccessfully": "آپ کا بیک اپ کامیابی سے ڈاؤن لوڈ ہو گیا۔",
  "backupFailed": "❌ بیک اپ ناکام",
  "backupCreationFailed": "بیک اپ بنانے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔",
  "restoringBackup": "بیک اپ بحال ہو رہا ہے...",
  "pleaseWaitRestore": "براہ کرم انتظار کریں جب ہم آپ کا ڈیٹا بحال کرتے ہیں۔",
  "restoreFailed": "❌ بحال کرنا ناکام",
  "restoreComplete": "✅ بحال کرنا مکمل",
  "dataRestoredSuccessfully": "آپ کا ڈیٹا کامیابی سے بحال ہو گیا۔ ایپ ۲ سیکنڈ میں ریفریش ہو جائے گی۔",
  "restoreFileCheckFailed": "بیک اپ بحال کرنے میں ناکام۔ براہ کرم فائل چیک کریں اور دوبارہ کوشش کریں۔",
  "cacheCleared": "کیش صاف",
  "deleteAllDownloadedBooks": "تمام ڈاؤن لوڈ شدہ کتابیں حذف کریں؟",
  "genderUpdated": "جنس اپ ڈیٹ ہو گئی",
  "menstrualModeAvailable": "ماہواری موڈ کی خصوصیات اب دستیاب ہیں۔",
  "preferencesUpdated": "آپ کی ترجیحات اپ ڈیٹ ہو گئی ہیں۔",
  "notificationPreferences": "نوٹیفیکیشن ترجیحات",
  "prayerNotifications": "نماز کی اطلاع",
  "ramadanCountdown": "رمضان کاؤنٹ ڈاؤن",
  "eidGreetings": "عید کی مبارکباد",
  "fridayKahfReminder": "جمعہ کہف کی یاددہانی",
  "morningReminders": "صبح کے اذکار",
  "eveningReminders": "شام کے اذکار",
  "testNotification": "ٹیسٹ نوٹیفیکیشن بھیجیں",
  "enableNotifications": "نوٹیفیکیشن فعال کریں",
  "notificationHistory": "نوٹیفیکیشن کی تاریخ",
  "compassIdle": "کمپس غیر فعال",
  "sensorNotActiveYet": "سینسر ابھی فعال نہیں ہے۔",
  "startingCompass": "کمپس شروع ہو رہا ہے",
  "holdPhoneSteady": "سینسر ڈیٹا شروع ہونے کے دوران اپنا فون مستحکم رکھیں۔",
  "liveCompassActive": "لائیو کمپس فعال",
  "liveHeadingDetected": "لائیو ہیڈنگ کا پتہ چلا اور اپ ڈیٹ ہو رہا ہے۔",
  "permissionRequired": "اجازت درکار ہے",
  "tapEnableCompass": "موشن سینسر اجازت کے لیے کمپس فعال کریں پر ٹیپ کریں۔",
  "compassPermissionDenied": "اجازت مسترد",
  "allowMotionAccess": "براؤزر یا ایپ ترتیبات میں موشن/اورینٹیشن رسائی کی اجازت دیں۔",
  "sensorUnsupported": "سینسر تعاون نہیں کرتا",
  "deviceNoCompassSensor": "یہ ڈیوائس اس ماحول میں کمپس سینسر کو ایکسپوز نہیں کرتا۔",
  "noSensorData": "کوئی سینسر ڈیٹا نہیں",
  "noOrientationEvents": "کوئی اورینٹیشن ایونٹس موصول نہیں ہوئے۔ نیچے دستی موڈ استعمال کریں۔",
  "detectingLocationQibla": "مقام اور قبلہ کی سمت کا پتہ لگایا جا رہا ہے...",
  "unableToStartQibla": "قبلہ شروع کرنے میں ناقابل",
  "pleaseTryAgain": "براہ کرم دوبارہ کوشش کریں۔",
  "retry": "دوبارہ کوشش کریں",
  "usePhysicalCompass": "ایک جسمانی کمپس استعمال کریں اور دستی قبلہ بیرنگ کا سامنا کریں۔",
  "alignedWithQibla": "قبلہ کے ساتھ ترتیب دیا",
  "turnRight": "دائیں مڑیں",
  "turnLeft": "بائیں مڑیں",
  "deg": "ڈگری",
  "enableCompass": "کمپس فعال کریں",
  "recalibrate": "دوبارہ کیلیبریٹ کریں",
  "manualMode": "دستی موڈ",
  "facingQibla": "قبلہ کا سامنا کرتا ہے",
  "kaabaDistance": "کعبہ کا فاصلہ",
  "currentBearing": "موجود بیرنگ",
  "qiblaDirection": "قبلہ کی سمت",
  "weeklyProgress": "ہفتہ وار پیش رفت",
  "prayersThisWeek": "اس ہفتے نمازیں",
  "noPrayerDataYet": "ابھی تک کوئی نماز کا ڈیٹا نہیں",
  "checkInPrayersToSeeProgress": "اپنی پیش رفت دیکھنے کے لیے نماز میں چیک کریں",
  "failedToLoadPrayerTimes": "نماز کے اوقات لوڈ کرنے میں ناکام",
  "tryAgain": "دوبارہ کوشش کریں",
  "useMecca": "مکہ استعمال کریں",
  "gps": "GPS",
  "defaultLocation": "ڈیفالٹ",
  "manualLocation": "دستی",
  "ishraqDuhaTahajjud": "اشراق، ضحی، تہجد...",
  "todaysSalah": "آج کی نماز",
  "dayStreak": "دن اسٹریک",
  "allPrayersCompletedToday": "✨ مashaAllah! آج تمام نمازیں مکمل ہو گئیں!",
  "digitalTasbeeh": "ڈیجیٹل تسبیح",
  "selectDhikr": "ذکر منتخب کریں",
  "total": "کل",
  "count": "شمار",
  "tapToDhikr": "ذکر کے لیے ٹیپ کریں",
  "resetCount": "شمار صاف کریں",
  "nextGoal": "اگلا ہدف",
  "resetCurrentCounter": "موجود کاؤنٹر کو ۰ پر ری سیٹ کریں؟",
  "alQuranAlKareem": "القرآن الکریم",
  "theNobleQuran": "القرآن الکریم",
  "readListenContemplate": "اللہ کے کلام پڑھیں، سنیں اور غور کریں۔",
  "continueReading": "پڑھنا جاری رکھیں",
  "searchBySurahNameOrNumber": "سورہ کے نام یا نمبر سے تلاش کریں...",
  "noSurahsFound": "آپ کی تلاش سے مطابق کوئی سورہ نہیں ملا۔",
  "quranReader": "قرآن ریڈر",
  "surahNotFound": "سورہ نہیں ملا",
  "quranSettingsButton": "ترتیبات",
  "progress": "پیش رفت",
  "quranSettings": "قرآن ترتیبات",
  "font": "فونٹ",
  "translation": "ترجمہ",
  "fontSize": "فونٹ سائز",
  "closeSettings": "ترتیبات بند کریں",
  "lastRead": "آخری پڑھا"
};

// Write Urdu translations to file
const localesDir = join(__dirname, '../locales');

try {
  mkdirSync(localesDir, { recursive: true });
  
  writeFileSync(
    join(localesDir, 'ur.json'),
    JSON.stringify(urduTranslations, null, 2),
    'utf8'
  );
  
  console.log('✅ Urdu translations populated successfully!');
} catch (error) {
  console.error('❌ Error populating Urdu translations:', error);
}
